#!/bin/bash
mv public/images/menu/vorspeisen/20-bruschetta-classico.png public/images/menu/vorspeisen/20-klassische-bruschetta.png
mv public/images/menu/vorspeisen/21-prosciutto-melone.png public/images/menu/vorspeisen/21-parmaschinken-mit-melone.png
mv public/images/menu/vorspeisen/22-la-burrata.png public/images/menu/vorspeisen/22-burrata.png
mv public/images/menu/vorspeisen/23-vitello-tonnato.png public/images/menu/vorspeisen/23-kalbfleisch-mit-thunfischsauce.png
mv public/images/menu/vorspeisen/24-carpaccio-manzo.png public/images/menu/vorspeisen/24-rindercarpaccio.png
mv public/images/menu/vorspeisen/25-antipasti-misti.png public/images/menu/vorspeisen/25-gemischte-vorspeisen.png
mv public/images/menu/salate/30-insalata-mista.png public/images/menu/salate/30-gemischter-salat.png
mv public/images/menu/salate/31-insalata-italia.png public/images/menu/salate/31-italienischer-salat.png
mv public/images/menu/salate/32-insalata-italia-klein.png public/images/menu/salate/32-italienischer-salat-klein.png
mv public/images/menu/salate/33-insalata-frutti-di-mare.png public/images/menu/salate/33-meeresfruechtesalat.png
mv public/images/menu/salate/34-insalata-pollo.png public/images/menu/salate/34-haehnchensalat.png
mv public/images/menu/salate/35-insalata-salmone-gamberoni.png public/images/menu/salate/35-lachs-und-garnelensalat.png
mv public/images/menu/salate/36-insalata-don-capo.png public/images/menu/salate/36-chef-salat.png
mv public/images/menu/pasta/42-rigatoni-puglia.png public/images/menu/pasta/42-rigatoni-apulien.png
mv public/images/menu/pasta/44-tagliatelle-verdure.png public/images/menu/pasta/44-bandnudeln-mit-gemuese.png
mv public/images/menu/pasta/45-tagliatelle-salmone.png public/images/menu/pasta/45-bandnudeln-mit-lachs.png
mv public/images/menu/pasta/46-linguine-frutti-di-mare.png public/images/menu/pasta/46-linguine-meeresfruechte.png
mv public/images/menu/pasta/47-linguine-pesce-misto.png public/images/menu/pasta/47-linguine-edelfisch.png
mv public/images/menu/pasta/48-pasta-combinazione.png public/images/menu/pasta/48-nudel-kombination.png
mv public/images/menu/pasta/49-rigatoni-al-ragu-e-verdure.png public/images/menu/pasta/49-rigatoni-mit-gemuese.png
mv public/images/menu/pasta/50-tortellini-alla-panna.png public/images/menu/pasta/50-tortellini-in-sahnesauce.png
mv public/images/menu/pasta/51-tortelacci-burro-e-salvia.png public/images/menu/pasta/51-tortellacci-butter-und-salbei.png
mv public/images/menu/pasta/52-tortellacci-salmone-e-gamberoni.png public/images/menu/pasta/52-tortellacci-lachs-und-garnelen.png
mv public/images/menu/pasta/53-gnocchi-con-gamberoni.png public/images/menu/pasta/53-gnocchi-mit-garnelen.png
mv public/images/menu/pasta/54-gnocchi-pesto-burrata.png public/images/menu/pasta/54-gnocchi-mit-basilikumpesto-und-burrata.png
mv public/images/menu/pasta/62-tortellini-prosciutto-e-panna.png public/images/menu/pasta/62-tortellini-mit-schinken-und-sahne.png
mv public/images/menu/fleisch-fisch/80-petto-di-pollo-alla-griglia.png public/images/menu/fleisch-fisch/80-gegrilltes-haehnchenbrustfilet.png
mv public/images/menu/fleisch-fisch/81-petto-di-pollo-al-pepe-verde.png public/images/menu/fleisch-fisch/81-haehnchenbrustfilet-in-gruener-pfeffersauce.png
mv public/images/menu/fleisch-fisch/82-filetto-di-maiale-al-vino-bianco.png public/images/menu/fleisch-fisch/82-schweinefilet-in-weisswein-zitronensauce.png
mv public/images/menu/fleisch-fisch/83-filetto-di-maiale-al-pepe-verde.png public/images/menu/fleisch-fisch/83-schweinefilet-in-gruener-pfeffersauce.png
mv public/images/menu/fleisch-fisch/84-bistecca-alla-griglia.png public/images/menu/fleisch-fisch/84-gegrilltes-rumpsteak.png
mv public/images/menu/fleisch-fisch/85-bistecca-al-pepe-verde.png public/images/menu/fleisch-fisch/85-rumpsteak-in-gruener-pfeffersauce.png
mv public/images/menu/fleisch-fisch/86-orata-con-burro-al-limone-e-aglio.png public/images/menu/fleisch-fisch/86-doradenfilet.png
mv public/images/menu/fleisch-fisch/87-salmone-alla-griglia-salsa-all-arancia-e-senape.png public/images/menu/fleisch-fisch/87-gegrilltes-lachsfilet.png
mv public/images/menu/fleisch-fisch/88-seppia-alla-griglia.png public/images/menu/fleisch-fisch/88-gegrillter-tintenfisch.png
mv public/images/menu/pizzen/90-pizza-margarita.png public/images/menu/pizzen/90-pizza-margherita.png
mv public/images/menu/pizzen/91-pizza-salame-e-funghi.png public/images/menu/pizzen/91-pizza-salami-und-champignons.png
mv public/images/menu/pizzen/97-pizza-parma-e-rucola.png public/images/menu/pizzen/97-pizza-parmaschinken-und-rucola.png
mv public/images/menu/pizzen/98-pizza-amore-mio-talia.png public/images/menu/pizzen/98-pizza-amore-mio.png
mv public/images/menu/pizzen/99-pizza-tonno.png public/images/menu/pizzen/99-pizza-thunfisch.png
mv public/images/menu/pizzen/100-pizza-burrata-e-rucola.png public/images/menu/pizzen/100-pizza-burrata-und-rucola.png
mv public/images/menu/pizzen/101-pizza-frutti-di-mare.png public/images/menu/pizzen/101-pizza-meeresfruechte.png
mv public/images/menu/pizzen/102-pizza-salmone-e-gamberoni.png public/images/menu/pizzen/102-pizza-lachs-und-garnelen.png
mv public/images/menu/pizzen/105-pizza-vegetale.png public/images/menu/pizzen/105-pizza-vegetarisch.png
mv public/images/menu/pizzen/106-pizzapane.png public/images/menu/pizzen/106-pizzabrot.png
mv public/images/menu/pizzen/113-familienpizza-tonno.png public/images/menu/pizzen/113-familienpizza-thunfisch.png
mv public/images/menu/pizzen/114-familienpizza-parma-e-rucola.png public/images/menu/pizzen/114-familienpizza-parmaschinken-und-rucola.png
mv public/images/menu/pizzen/115-familienpizza-vegetaria.png public/images/menu/pizzen/115-familienpizza-vegetarisch.png
mv public/images/menu/kindergerichte/121-rigatoni-burro.png public/images/menu/kindergerichte/121-rigatoni-mit-butter.png
mv public/images/menu/kindergerichte/122-spaghetti-alla-bolognese.png public/images/menu/kindergerichte/122-spaghetti-bolognese.png
mv public/images/menu/dessert/132-tartufo-nero.png public/images/menu/dessert/132-schokoladen-trueffeleis.png
mv public/images/menu/dessert/133-cassata-siciliana.png public/images/menu/dessert/133-sizilianische-eisspezialitaet.png
