/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        'xs': '375px',
      },
      colors: {
        onyx: {
          DEFAULT: '#1a1a2e',
          light: '#2d2d44',
          dark: '#0f0f1c',
          deep: 'var(--color-onyx-deep)',
        },
        'muted-gold': {
          DEFAULT: '#d4a843',
          light: '#e5c175',
          dark: '#C48810',
        },
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          950: 'var(--color-primary-950)',
          DEFAULT: 'var(--color-primary)',
          hover: 'var(--color-primary-hover)',
          active: 'var(--color-primary-active)',
        },
        accent: {
          50: 'var(--color-accent-50)',
          100: 'var(--color-accent-100)',
          200: 'var(--color-accent-200)',
          300: 'var(--color-accent-300)',
          400: 'var(--color-accent-400)',
          500: 'var(--color-accent-500)',
          600: 'var(--color-accent-600)',
          700: 'var(--color-accent-700)',
          800: 'var(--color-accent-800)',
          900: 'var(--color-accent-900)',
          950: 'var(--color-accent-950)',
          DEFAULT: 'var(--color-accent)',
          hover: 'var(--color-accent-hover)',
        },
        neutral: {
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
        },
        bg: {
          primary: 'var(--color-bg-primary)',
          secondary: 'var(--color-bg-secondary)',
          surface: 'var(--color-surface)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
        },
        status: {
          success: 'var(--color-success)',
          warning: 'var(--color-warning)',
          error: 'var(--color-error)',
          info: 'var(--color-info)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          hover: 'var(--color-border-hover)',
        },
        // Legacy support mapping to Rustikale Eleganz
        surface: 'var(--color-surface)',
        'accent-text': 'var(--color-accent-text)',
        'flame-red': 'var(--color-primary)',
        'flame-gold': 'var(--color-accent)',
        'flame-orange': 'var(--color-primary-hover)',
        'bg-dark': 'var(--color-bg-primary)',
        'bg-beige': 'var(--color-bg-primary)',
        'text-main': 'var(--color-text-primary)',
      },
      backgroundImage: {
        'brand-header': 'linear-gradient(135deg, var(--color-primary), var(--color-primary-dark, #5E0F18))',
        'brand-gold': 'linear-gradient(135deg, var(--color-accent), var(--color-accent-dark, #C48810))',
        'brand-bg': 'linear-gradient(180deg, var(--color-bg-primary), var(--color-bg-secondary))',
      },
      fontFamily: {
        sans: ['var(--font-body)', 'sans-serif'],
        body: ['var(--font-body)', 'sans-serif'],
        display: ['var(--font-heading)', 'serif'],
        heading: ['var(--font-heading)', 'serif'],
        mono: ['var(--font-family-mono)', 'monospace'],
        hand: ['var(--font-family-hand)', 'cursive'],
      },
      fontSize: {
        // Pipeline 2 Fluid Typo Scale
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
        '5xl': 'var(--text-5xl)',
        // Legacy Support
        display: ['var(--text-display)', { lineHeight: 'var(--leading-display)' }],
        h1: ['var(--text-h1)', { lineHeight: 'var(--leading-h1)' }],
        h2: ['var(--text-h2)', { lineHeight: 'var(--leading-h2)' }],
        h3: ['var(--text-h3)', { lineHeight: 'var(--leading-h3)' }],
        h4: ['var(--text-h4)', { lineHeight: 'var(--leading-h4)' }],
        hero: ['var(--text-display)', { lineHeight: 'var(--leading-display)' }],
      },
      lineHeight: {
        xs: 'var(--lh-xs)',
        sm: 'var(--lh-sm)',
        base: 'var(--lh-base)',
        lg: 'var(--lh-lg)',
        xl: 'var(--lh-xl)',
        '2xl': 'var(--lh-2xl)',
        '3xl': 'var(--lh-3xl)',
        '4xl': 'var(--lh-4xl)',
        '5xl': 'var(--lh-5xl)',
      },
      letterSpacing: {
        display: 'var(--ls-display)',
        heading: 'var(--ls-heading)',
        normal: 'var(--ls-body)',
        loose: 'var(--ls-small)',
        uppercase: 'var(--ls-uppercase)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-base)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        pill: 'var(--radius-pill)',
      },
      spacing: {
        0: 'var(--space-0)',
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        7: 'var(--space-7)',
        8: 'var(--space-8)',
        9: 'var(--space-9)',
        10: 'var(--space-10)',
        11: 'var(--space-11)',
        12: 'var(--space-12)',
        13: 'var(--space-13)',
        section: 'var(--space-section)',
        container: 'var(--space-container)',
        gap: 'var(--space-gap)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        'elevation-1': 'var(--shadow-elevation-01)',
        'elevation-2': 'var(--shadow-elevation-02)',
        'elevation-3': 'var(--shadow-elevation-03)',
        'elevation-4': 'var(--shadow-elevation-04)',
        'elevation-5': 'var(--shadow-elevation-05)',
      },
      transitionDuration: {
        instant: 'var(--duration-instant)',
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
        slower: 'var(--duration-slower)',
        slowest: 'var(--duration-slowest)',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
        in: 'var(--ease-in)',
        out: 'var(--ease-out)',
        'in-out': 'var(--ease-in-out)',
        bounce: 'var(--ease-bounce)',
        'ease-spring': 'var(--ease-spring)',
        'ease-smooth': 'var(--ease-smooth)',
        'liquid': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'liquid-slow': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      zIndex: {
        base: 'var(--z-base)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        overlay: 'var(--z-overlay)',
        modal: 'var(--z-modal)',
        toast: 'var(--z-toast)',
        tooltip: 'var(--z-tooltip)',
      },
      keyframes: {
        shine: {
          '100%': { transform: 'translateX(100%)' },
        },
      },
      animation: {
        shine: 'shine 1.5s cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
}
